GET http://{{host}}:{{port}}/api/fetch?mobileNumber={{mobileNumber}}
Accept: application/json

###
GET http://{{host}}:{{port}}/api/fetch?mobileNumber=123123123
Accept: application/json

###
POST http://{{host}}:{{port}}/api/create
Content-Type: application/json

{
  "name": "Hao Jiang",
  "email": "hi@hao.me",
  "mobileNumber": "0000000000"
}

###
PUT http://{{host}}:{{port}}/api/update
Content-Type: application/json


{
  "name": "Hao Jian",
  "email": "hao@neo42.me",
  "mobileNumber": "0000000001",
  "accountsDto": {
    "accountNumber": 1222977316,
    "accountType": "Current",
    "branchAddress": "124 Main Street, New York"
  }
}