GET http://{{host}}:{{port}}/api/fetch?mobileNumber={{mobileNumber}}
Accept: application/json

###
GET http://{{host}}:{{port}}/api/fetch?mobileNumber=123123123
Accept: application/json

###
POST http://{{host}}:{{port}}/api/create
Content-Type: application/json

{
  "name": "Hao Jiang",
  "email": "hi@hao.me",
  "mobileNumber": "0000000000"
}

###
